---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: quiz-service-dev
  namespace: apps
spec:
  encryptedData:
    DATABASE_PASSWORD: AgA6gJw31mPsMSjTm02kpL3kJ75BkNoKX7BIi+e0urkzUXmlYAktuQiBry0M0LYRJON7xVAk7g0cj0VTbkXhamt3YNGAzmDdG0SqS7ad+AVlQWhYy8K6xINs0h7Lmj+Y8mqzU+aqUt+VeR5FYNUxXOPzA1tYr42+DFxCWGL9JHQXTWtcg/jwqmSSqY5oNTvZqE9u74XWcWnO/wbpCQcHnlBsww48shmu5zCE28OvIOJfje+W4At38VkoXAvv6ijSBQVhLvK/5h9147lMIXo37v7wOkSJfyKUpRF33ud+7eGd9aLlC0HwGzOeQrZDmqN9xBjjkn+7oqi93Y5xYWxFYxb70BNqt1kVHnELbiAY5wOsHbHfjrsHaBPjIfWvqc813o6dqGnEjOUP4Ui6Z4fWsXu9xMMubOXfiH4PYu3c+ak9LfV2ptDJnn90MUiAne0Ix0QRJSfPL2zUa4JHf0Bce8hyngyj+/HTLn/PRY7Apa4rXrVsV5J/0olQUB4J1q6GFsjtgMp6q6uTnryQkzBGdiTCAtHM14G7FtrjyAtwLja1xs/OTZsM+qfFckb1W9cKboDFZU7n32Mn2JNDp/bsv2iPNmJSLdkoG2zmcPVVBM7rsbaLu0xrtAvkXMRUAnN4HX5zeslfInEJzEnaQzpd7smhlLWDjWxkrp/aX+Ubf8rtPGuljjMZG47ybRQA+imBDWv3qyB63KQs2zdt1FZk
    DATABASE_USER: AgC6HVj8hTLqIrR5PvEblezGc0v/ZYG4R2/sVgHTaj+QGFLH8UUu9UZICfcXt3RFjZHlpEe041QDiCHv6Ar2D1UswqAdU12yn8JqDz0H7rA5IfqICqUNdPC8nKJWwT/uVldxUqvoAa5iK6WPhDTf/ggbQub2sN/2i0VBiCz+Bgm0rcOXOSKLV38UiNzR1KAtpOisp/HC9+wFvBCW4s3KCcXxresjvZe81Q1ZY8aFedn36/AKw5cETbpZoCd57d6NqsItT0tEWZ9qiRG9NBqJHf9yMvK01ICaYAa4LErfqcfgBBWWnaO7gqtlZphIQyVm5zjYUV3c0MKEzzGHk7MZ0+p7TBmRW//WOnDauRT21SlTUCiY1lTD0FBldsLROhL0kEuuQTr8kRVW4fOlnnmABYzHWtwfpP8JUXzv2FuE2EW+9riKpeaXgp44oZ05PzY6VGc6PUQgKKJWtgXTufUHIx2uYcZl/bQYgdzPe4ub2xLm2kXV7hUenM3rqaaO4QxaX1TVTYS3RkI2fLPb+uvuSIiCcDwSqU/Wf6aPkwCpZXsnTTmSIcnSse9NBrxrXh2CI90XnBh7TATNXQ/wlzrJ148oRMO6Yo/lonCQMipoh7+P/E6sGyKn4yCCJ4EUwE93R56VmB/A3AnHdKCM37jCQijcwfloxtZwcwWG2y65ii0Nl4qFCwet7hejIGZ3NWMXyk98Dtdgeo+b8Rw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: quiz-service-dev
      namespace: apps
