apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  timeoutSec: 300
  customRequestHeaders:
    headers:
      - "Connection: keep-alive"
  cdn:
    enabled: false
