image:
  repository: docker.elastic.co/kibana/kibana
  tag: 8.11.0
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  port: 5601
  loadBalancerSourceRanges:
    - "112.186.245.109/32"
    - "220.120.36.185/32"
    - "183.101.19.11/32"
    - "210.96.46.172/32"