apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-logstash-config
data:
  logstash.yml: |
{{ .Files.Get "config/logstash.yml" | indent 4 }}

  pipelines.yml: |
{{ .Files.Get "config/pipelines.yml" | indent 4 }}

  pipeline.conf: |
{{ .Files.Get "config/pipeline.conf" | indent 4 }}