apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-chart.fullname" . }}
  labels:
    {{- include "redis-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "redis-chart.selectorLabels" . | nindent 4 }}