global:
  storageClass: premium-rwo-retain-zonal
  imageRegistry: "asia-northeast3-docker.pkg.dev/quizy-442816/quizy"

kafka:
  replicaCount: 3
  logsDirs: /bitnami/kafka/logs
  deleteTopicEnable: true
  persistence:
    size: 1Gi
  heapOpts: -Xmx512m -Xms512m
  metrics:
    kafka:
      enabled: false
  zookeeper:
    replicaCount: 1
    metrics:
      enabled: false
    persistence:
      size: 1Gi
zookeeper:
  persistence:
    size: 1Gi
serviceAccount:
  create: true
  name: "ksa-kafka1"
  annotations: {}

storageClass:
  create: true
  name: premium-rwo-retain-zonal
  parameters:
    type: pd-standard

kafkaUi:
  enabled: true
  image:
    repository: provectuslabs/kafka-ui
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
  envs:
    - name: KAFKA_CLUSTERS_0_NAME
      value: quizy-cluster
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: kafka.kafka.svc.cluster.local:9092
    - name: KAFKA_CLUSTERS_0_ZOOKEEPER
      value: kafka-zookeeper.kafka.svc.cluster.local:2181

ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "kafka-ui-ip"
  hosts:
    - host: ""  # 빈 문자열은 모든 호스트를 의미
      paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: kafka-ui
              port:
                number: 80



