# Default values for quiz-service-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: asia-northeast3-docker.pkg.dev/civic-champion-442512-n9/quizy/game-service
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "b69f7151ad4fb1f366782be45c6453ecf970bb42-12175082853"
# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
fullnameOverride: "dev-game-service"
# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8080
  targetPort: 8080
env: dev
envs:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: DATABASE_HOST
    value: "mysql-mysql.mysql.svc.cluster.local"
  - name: DATABASE_NAME
    value: "game"
  - name: JPA_DDL_AUTO
    value: "create"
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: user-service-dev
        key: DATABASE_USER
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: user-service-dev
        key: DATABASE_PASSWORD
  - name: REDIS_HOST
    value: "redis.redis.svc.cluster.local"
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: "kafka.kafka.svc.cluster.local:9092"
