# values.yaml
replicaCount: 1

image:
  repository: jiwonkkang/debezium-connect
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083

configStorage:
  topic: kafka-connect-configs
  replicationFactor: 1

offsetStorage:
  topic: kafka-connect-offsets
  replicationFactor: 1

statusStorage:
  topic: kafka-connect-status
  replicationFactor: 1

kafka:
  bootstrapServers: "kafka.kafka.svc.cluster.local:9092"
  zookeeperConnect: "kafka-zookeeper.kafka.svc.cluster.local:2181"