# Default values for quiz-service-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: 358279808022.dkr.ecr.ap-northeast-2.amazonaws.com/quizy
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "bf53a190a8f966cf0ebb32b804f27e8c854c6b8b-11789458191"
# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
fullnameOverride: "dev-quiz-service"
# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8080
  targetPort: 8080
env: dev
envs:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: DATABASE_HOST
    value: "quizy-k8s-resource-rds.c1g6swmoyqe1.ap-northeast-2.rds.amazonaws.com"
  - name: DATABASE_PORT
    value: "3306"
  - name: DATABASE_NAME
    value: "quiz"
  - name: JPA_DDL_AUTO
    value: "create"
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: quiz-service-dev
        key: DATABASE_USER
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: quiz-service-dev
        key: DATABASE_PASSWORD
