# Default values for quiz-service-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: asia-northeast3-docker.pkg.dev/civic-champion-442512-n9/quizy/quiz-service
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "351b62cca47002781321993d2e9d651edd30c4fb-12201697757"
# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
fullnameOverride: "dev-quiz-service"
# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8080
  targetPort: 8080
env: dev
envs:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: DATABASE_HOST
    value: mysql-mysql.mysql.svc.cluster.local
  - name: DATABASE_NAME
    value: "quiz"
  - name: JPA_DDL_AUTO
    value: "update"
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: quiz-service-dev
        key: DATABASE_USER
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: quiz-service-dev
        key: DATABASE_PASSWORD
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: kafka.kafka.svc.cluster.local:9092
  - name: REDIS_HOST
    value: redis.redis.svc.cluster.local
  - name: ELASTICSEARCH_HOST
    value: elk-elasticsearch.elk.svc.cluster.local
  - name: GCP_PROJECT_ID
    valueFrom:
      secretKeyRef:
        name: user-service-dev
        key: GCP_PROJECT_ID
  - name: BUCKET_NAME
    valueFrom:
      secretKeyRef:
        name: user-service-dev
        key: BUCKET_NAME
  - name: GCS_KEY
    valueFrom:
      secretKeyRef:
        name: user-service-dev
        key: GCS_KEY
  - name: LOGSTASH_HOST
    value: elk-logstash.elk.svc.cluster.local
  - name: LOGSTASH_PORT
    value: "5044"
  - name: GCP_CDN_DOMAIN
    value: quizy-cdn.n-e.kr
