---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: user-service-dev
  namespace: apps
spec:
  encryptedData:
    DATABASE_PASSWORD: AgC56Cg4ICR7+LvkmjoQWyfZNbwn9UFaFG/XE2uk8WK0QP1wSD04Mg946p3OHDc3vkTbWIQ/gGCgYCQHLt5cE+HaL3lWnm+3uGsV6odXZfLlXELic3PpxfbxTZVWo/hBKsqBzcwneA8WUJYaysCt6nve36LAdDrTXwDocFDifzMEnB00PbFbjwFep0reUtC4ecXR/8NwCKdl/A1BilGS3pY93kaMg2E5xQMcofiE10Bp6iE9Y+EYql0zv8fQW6bFgYnqdKI5SuIngN1SzhUj/8OpM/0/SVy+tNR5PlykXcZJkBMEZrA93gF4LF65YTHVYxvR31AtqHlXCVe4aZQ+/is9sOGcFPVvXpLsYKj8vTDOz8OLFiq06k0hjUsqwwRPZnDejP4Cj5+zDczd8NI1tRUb5IHvkgx3ORIdNyMDaQw2/4GN775LLrqiSlC4gYC6RF3gB3cw9pVp5WmrOE+XQWeRIP5123cG7EXiw/NYf+jlInWih9QxDyzZPNnZmyBjI6jUjdUd8Y024oZ1O0L6xEp6dcmWaR6RTAYZ07eok0WRLfLg/5bsbieyVryZll3l+L8yZfZ6uzXdtUDZS8HzJd9ld3BEieAhAJoS7EgBoRlgKd7wHf78OuohaTc75ooge2iYdzuM7XUoA2CgFM8w4TFerq6BpT+Je4FqH99P12+uFtsXEafRyvDjScHP2LhTexJWl96ciy/A
    DATABASE_USER: AgAMrLLCA+M9E0Xt/0DXDCQZvUTwmgvf6qYdibmFZ+LtTKlssQt68EOwqSOsJDsnEQYGpEhaKU5hmPaXGVPNPU/rmClr79whBt3n8JnDtMwD8qOISzi3i/rpMgewhsQewgig3VgHTaWOVXPx+ofMAtVMeTS07q4Avj3kvT7cN9JZOGNnrUDoq40rYtTmjCZA/D4q2vlcSK/jWN5v+y770HhMJfD6y5Uc3VxExQObzonjvGouT3Rp5pTyV31aQrTGFvakLfZ/37473SRcwiRCbNgZ9efiqKRiGwZS7a6RxmC4xT+qj5NrITq8gfYJokMvUHr88gb2zmT29D8ZOlWBTIR9KUmDVU7oecrC9hKyzqeAxL5bNwaBntvFNM3vBITBxhVIft2cDXsK2qilMReleSBsG/ISGMisYHpaR4q7LY+QANFVuNSAdwcFdRfD3ey8k+JyqZm+KW7an4oIluYOCfcCRpsWUi3rptOGxSL9aBQAs3YhqwtjfG+CGOQkXNMMO0kQIZS6heS8iLXYl9i4cnol6ZAS38aG2sjbeu3dqHYCdUGo7j9LzdLwpFSNT8SpuDc+cPUh/b0XWzpU4WUbVBB3WFGMqq+KDcVYwvIGrm9zUxqtrNgJBDKe/Ou2Zwm84t6tjrfcvJl558wt6K0Dap2xLBbk3T3vlUju9EbCep2frYm9szTIy1ojK0q61fvKypFdqndjD7tsTII=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: user-service-dev
      namespace: apps
