apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kibana
  labels:
    app: kibana
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://{{ .Release.Name }}-elasticsearch:9200
          ports:
            - containerPort: 5601
              name: http